### ISSUE TITLE
Can't set up JMIN and JMAX env variables

### ISSUE THREAD

**Issue by TheSainEyereg** [w0rng/amnezia-wg-easy#13]
Here is my `docker-compose.override.yml` file's content:
```yaml
  amnezia-wg-easy:
    extends:
      file: docker-compose.wireguard-amnezia.yml
      service: amnezia-wg-easy
    environment:
      - WG_PORT=8443
      - JC=5
      - JMIN=40
      - JMAX=70
    ports: !override
      - 8443:8443/udp
      - 51821:51821/tcp
```

Should work fine according to README, but all configs downloaded from web UI has default `Jmin` and `Jmax` values in it
