### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by orihomie** [w0rng/amnezia-wg-easy#20]
As in original repo, no internet connection after launching both via `docker run` and `docker compose up`:

I download conf file, import it to AmneziaVPN app and then after connecting to VPN just trying to open any site and nothing works.

I've retested on different servers simply by running docker container from readme, issue is the same — not working.

**Comment by Ernieleo** [comment]
Can you provide more details, maybe I can help you. What are the allowed IPs in the config (range)?

**Comment by foogs** [comment]
Same, i reinstall this on ubuntu 24 and it borked, no internet

**Comment by janusloo** [comment]
Hi I am also trying to make it work in a docker container. I run my own DNS servers and configured them to use in AmneziaWG. It does not work, no internet. Then I changed the default dns server to 1.1.1.1 but it still does not work.

I did open a port forwarding for 51880 from the router to the AmneziaWG.

This is my configuration:
```
services:
  amnezia-wg-easy:
    env_file:
      - .env
    image: ghcr.io/w0rng/amnezia-wg-easy
    container_name: amnezia-wg-easy
    volumes:
      - /volume1/docker/appdata/amnezia-wg-easy:/etc/wireguard
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
      - "${PORT}:${PORT}/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    devices:
    - /dev/net/tun:/dev/net/tun
volumes:
  etc_wireguard:
```

.env:
```
WG_HOST=xxx.xxx.com
# (Supports: en, ru, tr, no, pl, fr, de, ca, es)
LANGUAGE=en
PORT=51821
WG_DEVICE=eth0
WG_PORT=51880
WG_DEFAULT_ADDRESS=10.8.0.x
WG_DEFAULT_DNS=1.1.1.1
WG_ALLOWED_IPS=0.0.0.0/0
DICEBEAR_TYPE=bottts
USE_GRAVATAR=false
PASSWORD_HASH=$$$

```

I just wondered what have I missed here? Can you please give a guidance? Thanks!
