### ISSUE TITLE
Can't access Prometheus metrics

### ISSUE THREAD

**Issue by Mesqu1te** [w0rng/amnezia-wg-easy#31]
When I try to add a new Prometheus data source in Grafana, I get the following error:
**405 Method Not Allowed - There was an error returned querying the Prometheus API.**
Metrics is running and accessible from the browser (tested via curl and direct IP:port). The error appears when Grafana attempts to query the Prometheus endpoint.

**Comment by epsilon-pluto** [comment]
http://0.0.0.0:51821/metrics  - Metrics for Prometheus.
you need to run Prometheus and read data from 0.0.0.0:51821/metrics
then you can use your running Prometheus  server in Grafana

Here's a complete docker-compose.yml that runs Prometheus and scrapes metrics from your server (which is protected by Basic Auth at /metrics). This setup does not include Grafana yet — just Prometheus scraping your app.

✅ docker-compose.yml

```
version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Optional: replace this with your actual service
  # mock_server:
  #   image: your_app_image
  #   environment:
  #     - USERNAME=your_username
  #     - PASSWORD=your_password
  #   ports:
  #     - "8000:8000"
```
✅ prometheus.yml
Place this file next to the docker-compose file:

```
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'metrics'
    static_configs:
      - targets: ['host.docker.internal:51821']  # change to your server's host/IP if needed
    basic_auth:
      username: 'your_username' #use empty! ''
      password: 'your_password'

```
📝 Notes
host.docker.internal works if Prometheus is inside Docker, and your app is running on the host machine (Windows/Mac/Linux with Docker Desktop).

If your app is in another Docker container, you’ll need to:

put both in the same Docker network

use the container name as the hostname (e.g. my-app:8000)

Replace your_username / your_password with real credentials.

🚀 Run it
From the same directory:
`docker-compose up -d`

Then open Prometheus UI:
http://localhost:9090

Im my case i put follow url http://host.docker.internal:9090
to Grafana connection section => Prometheus server URL

<img width="1109" alt="Image" src="https://github.com/user-attachments/assets/ebbf48b1-d976-4b04-ba6f-fb15848479d4" />
